server:
  port: 30612
  prefix: /tool/server
  log:
    # 0: Panic 1: Fatal 2: Error 3: Warn 4: Info 5: Debug 6: Trace
    level: 4

database:
  source: db/server.db
  maxIdleConn: 50
  maxOpenConn: 100
  connMaxLifeTime: 3600
