navigation:
#  - title: 通用工具
#    id: 100000
#    describe: "通用工具合集"
#    icon: "test"
#    href: "test"
#    children:
#      - title: "PDF合并工具"
#        id: 100001
#        describe: "多个PDF合并为同一个PDF"
#        icon: "test"
#        href: "test"
  - title: Windows工具
    id: 200000
    describe: "Windows工具合集"
    icon: "https://tse4-mm.cn.bing.net/th/id/OIP-C.KCC7Q_I7oFzYEgVwxqv1egHaEM?pid=ImgDet&rs=1"
    href: "https://tse4-mm.cn.bing.net/th/id/OIP-C.KCC7Q_I7oFzYEgVwxqv1egHaEM?pid=ImgDet&rs=1"
    children:
      - title: "windows11优化"
        id: 200001
        describe: "Windows11优化"
        icon: "https://tse4-mm.cn.bing.net/th/id/OIP-C.KCC7Q_I7oFzYEgVwxqv1egHaEM?pid=ImgDet&rs=1"
        href: "https://tse4-mm.cn.bing.net/th/id/OIP-C.KCC7Q_I7oFzYEgVwxqv1egHaEM?pid=ImgDet&rs=1"